[package]
name = "whois-rust"
version = "1.1.9"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/whois-rust"
homepage = "https://magiclen.org/whois-rust"
keywords = ["whois"]
categories = ["web-programming::websocket"]
description= "This is a WHOIS client library for Rust, inspired by https://github.com/hjr265/node-whois"
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/whois-rust"
branch = "master"

[dependencies]
serde_json = "1.0"
regex = "1.0"
lazy_static = "1.1.0"
idna = "0.2"
async-std = "1.4"

[dependencies.validators]
version = ">=0.19,<0.21"
features = ["serdely"]